/**
 * The enum Tipos habilidades.
 */
public enum TiposHabilidades {
    CARISMA, DESTREZA, EMPATIA, ENCANTO, FUERZA_VOLUNTAD, INTELECTO, PERCEPCION, RAPIDEZ, RESISTENCIA, SABIDURIA, SUERTE
    , VITALIDAD, NONE

}
